name: 'Docker Image/Tag Exists'
description: 'Check if a Docker image/tag exists in Docker Hub'
inputs:
  name-and-tag:
    description: 'Docker image name with tag (e.g., username/image:tag)'
    required: true
  dockerhub-username:
    description: 'DockerHub username for authentication'
    required: true
  dockerhub-password:
    description: 'DockerHub password or access token'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    - name: Check if Docker image/tag exists
      shell: bash
      id: check_image_tag
      run: |
        set -e
        echo "Checking if image/tag exists: ${{ inputs.name-and-tag }}"
        docker manifest inspect ${{ inputs.name-and-tag }}